### ISSUE TITLE
Bot won't start, seems not to read Bot.js

### ISSUE THREAD

**Issue by LastNarrator** [renesansz/discord-greeter-bot#10]
log (using git bash cause idk how to open CMD in specific foler)

$ node bot.js
module.js:471
    throw err;
    ^

Error: Cannot find module 'E:\Discord Bots\Kill Bot\bot.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3

**Comment by LastNarrator** [comment]
Nevermind, found the problem, it saved them as .txt not .js or .json
