### ISSUE TITLE
Node.js not working, gives me errors instead.

### ISSUE THREAD

**Issue by sneezy02** [renesansz/discord-greeter-bot#101]
I'll admit I've got no experience in this area and the tutorial says its for people who have some experience, but I'm a quick learner and I would really like to continue this project so any help would be amazing.

I went and searched through all the other errors like this and I've come to the point where I can't find any more possible fixes and I keep getting this error in the CMD:

C:\Users\Adam\Desktop\DiscordBot>node bot.js
module.js:549
    throw err;
    ^

Error: Cannot find module 'winston'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Adam\Desktop\DiscordBot\bot.js:2:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

I tried to use #44 and #48 to fix it but I've got no idea what to do now. Does anyone have a clue? I've reinstalled git a few times already and I've installed it to run with the cmd but that didn't change anything.

**Comment by sneezy02** [comment]
Nevermind! I decided to dig a little further and read every "node.js not working" thread I could and #88 absolutely saved me!
