### ISSUE TITLE
bot crashes when receives DM

### ISSUE THREAD

**Issue by vaginas** [renesansz/discord-greeter-bot#106]
I was playing with the bot and noticed if someone sends the bot a direct message it will show this

```
        this.guild_id = server.id;
                               ^

TypeError: Cannot read property 'id' of undefined
    at new Channel (/home/pi/discord-greeter-bot/node_modules/discord.io/lib/index.js:2529:25)
    at DiscordClient.handleWSMessage (/home/pi/discord-greeter-bot/node_modules/discord.io/lib/index.js:1889:33)
    at WebSocket.emit (events.js:180:13)
    at Receiver.ontext (/home/pi/discord-greeter-bot/node_modules/ws/lib/WebSocket.js:841:10)
    at /home/pi/discord-greeter-bot/node_modules/ws/lib/Receiver.js:536:18
    at Receiver.applyExtensions (/home/pi/discord-greeter-bot/node_modules/ws/lib/Receiver.js:371:5)
    at /home/pi/discord-greeter-bot/node_modules/ws/lib/Receiver.js:508:14
    at Receiver.flush (/home/pi/discord-greeter-bot/node_modules/ws/lib/Receiver.js:347:3)
    at Receiver.finish (/home/pi/discord-greeter-bot/node_modules/ws/lib/Receiver.js:541:12)
    at Receiver.expectHandler (/home/pi/discord-greeter-bot/node_modules/ws/lib/Receiver.js:499:31)

```
And crashes...
Any way to avoid this?

EDIT: Not a major issue.
I made a bash script that can see if the bot is running or not. And if the bot is not running it launches it again.
I run this bash script as a cron job. So the bot it will always came back.

**Comment by Mrthomas20121** [comment]
it doesn't work because you don't have the update version of the script. use this to make it work :)
npm install https://github.com/woor/discord.io/tarball/gateway_v6

**Comment by axelgreavette** [comment]
Actually it doesn't work because DM's have no Server ID. Updating will not help, however the Discord.io Support Server can. It can be found [here](https://discord.gg/pHcq66n)
