### ISSUE TITLE
I have a problem with the node bot.js

### ISSUE THREAD

**Issue by MR-KARPIN** [renesansz/discord-greeter-bot#123]
When I write node bot.js it appears this, pls help, thanks

bot.js:1
(function (exports, require, module, __filename, __dirname) { ar Discord = require('discord.io');
                                                                 ^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

**Comment by MR-KARPIN** [comment]
ok now its doesnt show anything xd

**Comment by MR-KARPIN** [comment]
ok is fixed hahaha
