### ISSUE TITLE
Issue with bot

### ISSUE THREAD

**Issue by zRattly** [renesansz/discord-greeter-bot#125]
I tryed to host this bot on glitch.com
Error code:
$ node bot.js
/rbd/pnpm-volume/137f840e-4cc6-497b-a313-fbf0ace6613a/node_modules/.registry.npmjs.org/winston-transport/4.2.0/node_modules/winston-transport/legacy.js:18
    throw new Error('Invalid transport, must be an object with a log method.');
    ^
Error: Invalid transport, must be an object with a log method.
    at new LegacyTransportStream (/rbd/pnpm-volume/137f840e-4cc6-497b-a313-fbf0ace6613a/node_modules/.registry.npmjs.org/winston-transport/4.2.0/node_modules/winst
on-transport/legacy.js:18:11)
    at DerivedLogger.add (/rbd/pnpm-volume/137f840e-4cc6-497b-a313-fbf0ace6613a/node_modules/.registry.npmjs.org/winston/3.0.0/node_modules/winston/lib/winston/log
ger.js:245:9)
    at Object.winston.(anonymous function).args [as add] (/rbd/pnpm-volume/137f840e-4cc6-497b-a313-fbf0ace6613a/node_modules/.registry.npmjs.org/winston/3.0.0/node
_modules/winston/lib/winston.js:101:55)
    at Object.<anonymous> (/app/bot.js:6:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)

**Comment by pacucci** [comment]
lol

**Comment by sarthaktexas** [comment]
First of all, did you install all the dependencies? Second of all, I don't think you can host it on glitch.com

**Comment by renesansz** [comment]
@zRattly You need to host it on a server, I don't think glitch.com support this kind of hosting for your bot.
Closing issue
