### ISSUE TITLE
node bot.js doesnt work (ERRORs)

### ISSUE THREAD

**Issue by Dziugasc** [renesansz/discord-greeter-bot#127]
C:\Users\Admin\Desktop\XDBot>node bot.js
C:\Users\Admin\Desktop\XDBot\node_modules\winston-transport\legacy.js:18
    throw new Error('Invalid transport, must be an object with a log method.');
    ^

Error: Invalid transport, must be an object with a log method.
    at new LegacyTransportStream (C:\Users\Admin\Desktop\XDBot\node_modules\winston-transport\legacy.js:18:11)
    at DerivedLogger.add (C:\Users\Admin\Desktop\XDBot\node_modules\winston\lib\winston\logger.js:245:9)
    at Object.winston.(anonymous function).args [as add] (C:\Users\Admin\Desktop\XDBot\node_modules\winston\lib\winston.js:101:55)
    at Object.<anonymous> (C:\Users\Admin\Desktop\XDBot\bot.js:6:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)

**Comment by zachwright** [comment]
Specifically, the issue is that it appears this tutorial was written during Winston v2.x and in 2018 we have Winston v3.0.x, so there are API changes not highlighted in the tutorial.

This has documentation for v3.x:
https://github.com/winstonjs/winston

This highlights upgrade issues:
https://github.com/winstonjs/winston/blob/master/UPGRADE-3.0.md

From the docs: 
// DON'T DO THIS. It will no longer work
logger.add(winston.transports.Console);

// Do this instead.
logger.add(new winston.transports.Console());

**Comment by JoJoshiro** [comment]
I've been following a basic tutorial to create a simple greeter bot for discord before jumping into more complex actions, but I can't seem to figure out why it's not going through. I've attempted all the suggestions that have been posted in this thread, but still getting errors.

C:\Users\Administrator\Desktop\discordbot>npm install discord.io github:woor/discord.io#gateway_v6 winston --save
npm WARN greeter-bot@1.0.0 No repository field.
npm WARN greeter-bot@1.0.0 No license field.

+ winston@3.0.0
+ discord.io@2.5.3
+ discord.io@2.5.3
updated 2 packages in 3.156s

C:\Users\Administrator\Desktop\discordbot>node bot.js
C:\Users\Administrator\Desktop\discordbot\bot.js:40
});
^

SyntaxError: Unexpected token }
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
