### ISSUE TITLE
Node bot.js Creating Errors

### ISSUE THREAD

**Issue by Spookl** [renesansz/discord-greeter-bot#137]
Every time that I run node bot.js errors will come back as:
C:\Users\user\Documents\Discord Bot\node_modules\winston-transport\legacy.js:18
    throw new Error('Invalid transport, must be an object with a log method.');
    ^

Error: Invalid transport, must be an object with a log method.
    at new LegacyTransportStream (C:\Users\user\Documents\Discord Bot\node_modul
es\winston-transport\legacy.js:18:11)
    at DerivedLogger.add (C:\Users\user\Documents\Discord Bot\node_modules\winst
on\lib\winston\logger.js:245:9)
    at Object.winston.(anonymous function).args [as add] (C:\Users\user\Document
s\Discord Bot\node_modules\winston\lib\winston.js:101:55)
    at Object.<anonymous> (C:\Users\user\Documents\Discord Bot\bot.js:6:8)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)

I myself have very little knowledge of Javascript so i'm not sure what the problem could be so any help would be greatly appreciated

**Comment by axlplayer21** [comment]
https://github.com/renesansz/discord-greeter-bot/issues/127

See reply from lawrenceone

> Make the change in line 6, it should look like this
logger.add(new logger.transports.Console, { colorize: true });
and run the below and it should work ;)
npm install discord.io github:woor/discord.io#gateway_v6 winston --save

**Comment by FunkyNeonChickN** [comment]
Thank you this helped me too!

**Comment by nelsonojr** [comment]
I had this trouble becouse winston 3.0.0 is not compatible. Put the code in the package.json file and reinstal.

`    "discord.io": "https://github.com/woor/discord.io/tarball/gateway_v6",
    "winston": "^2.4.3"`
