### ISSUE TITLE
I got this error.

### ISSUE THREAD

**Issue by Explictian** [renesansz/discord-greeter-bot#149]
alexs-MacBook-Pro:SparkBot alex$ node bot.js
/Users/alex/Desktop/SparkBot/node_modules/winston-transport/legacy.js:18
    throw new Error('Invalid transport, must be an object with a log method.');
    ^

Error: Invalid transport, must be an object with a log method.
    at new LegacyTransportStream (/Users/alex/Desktop/SparkBot/node_modules/winston-transport/legacy.js:18:11)
    at DerivedLogger.add (/Users/alex/Desktop/SparkBot/node_modules/winston/lib/winston/logger.js:245:9)
    at Object.winston.(anonymous function).args [as add] (/Users/alex/Desktop/SparkBot/node_modules/winston/lib/winston.js:101:55)
    at Object.<anonymous> (/Users/alex/Desktop/SparkBot/bot.js:6:8)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)

**Comment by nelsonojr** [comment]
I have the same error.

**Comment by jamppu** [comment]
Yep, same here
