### ISSUE TITLE
node bot cannot find auth

### ISSUE THREAD

**Issue by Threnix** [renesansz/discord-greeter-bot#153]
When running node bot.js, I keep getting the error that it cannot find auth.json module. I've also tried adding the full location to the requirement in bot.js, which changes what it's looking for but throws the same error. Any thoughts?

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module './auth.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\JLD\Desktop\MODDING\Discord Bots\ROBOTHRENIX\bot.js:3:12)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

**Comment by KaushalGangwar** [comment]
You are getting this error because auth.json is not present. Try after creating a auth.json and adding the token
