### ISSUE TITLE
i had a problem when trying node bot.js

### ISSUE THREAD

**Issue by RaGamerz** [renesansz/discord-greeter-bot#154]
when i tried to type node bot.js in my command prompt, it shows these messages.
    throw new Error('Invalid transport, must be an object with a log method.');
    ^

Error: Invalid transport, must be an object with a log method.
    at new LegacyTransportStream (E:\MyFiles\DiscordBot\node_modules\winston-tra
nsport\legacy.js:18:11)
    at DerivedLogger.add (E:\MyFiles\DiscordBot\node_modules\winston\lib\winston
\logger.js:245:9)
    at Object.winston.(anonymous function).args [as add] (E:\MyFiles\DiscordBot\
node_modules\winston\lib\winston.js:101:55)
    at Object.<anonymous> (E:\MyFiles\DiscordBot\bot.js:6:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)

**Comment by Asshritt** [comment]
I had this error, it comes from :
`logger.add(logger.transports.Console, {
    colorize: true
});`
You need to add `new` before `logger.transports.Console`

--> `logger.add(new logger.transports.Console, {`
