### ISSUE TITLE
node bot.js isn't working

### ISSUE THREAD

**Issue by MrRjLeddbearl** [renesansz/discord-greeter-bot#159]
When I put in node bot.js I was given this error message

Error: Cannot find module 'C:\Users\REDACTED\Desktop\REDACTED\Usagi bot\bot.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)

REDACTED text is just my name.

**Comment by SLia0** [comment]
Make sure bot.js is not actually bot.js.txt! In file explorer go to view and check "file name extensions".
