### ISSUE TITLE
I get this error after node bot.js

### ISSUE THREAD

**Issue by honknuu** [renesansz/discord-greeter-bot#163]
pls helpme,,,
![Aaa](https://i.imgur.com/PubLBwd.png)
edited because i solved the previous error

- Error: Invalid transport, must be an object with a log method.
    at new LegacyTransportStream (C:\Users\Alumno\Desktop\DiscordBot\node_modules\winston-transport\legacy.js:18:11)
    at DerivedLogger.add (C:\Users\Alumno\Desktop\DiscordBot\node_modules\winston\lib\winston\logger.js:245:9)
    at Object.winston.(anonymous function).args [as add] (C:\Users\Alumno\Desktop\DiscordBot\node_modules\winston\lib\winston.js:101:55)
    at Object.<anonymous> (C:\Users\Alumno\Desktop\DiscordBot\bot.js:6:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)

**Comment by Tbalta** [comment]
the answer is write, there is atoken in auth.json at the third letter, check if you did not reverse auth.json and package.json
