### ISSUE TITLE
Having a Problem About node bot.jk

### ISSUE THREAD

**Issue by BirdKun** [renesansz/discord-greeter-bot#166]
Problem:

C:\Users\My Username\Desktop\MyBot\node_modules\winston-transport\legacy.js:18
    throw new Error('Invalid transport, must be an object with a log method.');
    ^

Error: Invalid transport, must be an object with a log method.
    at new LegacyTransportStream (C:\Users\Orlando Solar\Desktop\MyBot\node_modules\winston-transport\legacy.js:18:11)
    at DerivedLogger.add (C:\Users\Orlando Solar\Desktop\MyBot\node_modules\winston\lib\winston\logger.js:245:9)
    at Object.winston.(anonymous function).args [as add] (C:\Users\Orlando Solar\Desktop\MyBot\node_modules\winston\lib\winston.js:101:55)
    at Object.<anonymous> (C:\Users\Orlando Solar\Desktop\MyBot\bot.js:6:8)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)

**Comment by BaconWrappedShrimpWithEyes** [comment]
On line 9 of bot.js add it should be 
`logger add(new logger.Transports.console, {`
so just add new to the file

**Comment by akshaynexus** [comment]
Thanks @BaconWrappedShrimpWithEyes ,got my issue fixed
