### ISSUE TITLE
Node bot.js Issue

### ISSUE THREAD

**Issue by s51tine** [renesansz/discord-greeter-bot#170]
C:\Users\Janez\Desktop\DiscordBot\node_modules\winston-transport\legacy.js:18
    throw new Error('Invalid transport, must be an object with a log method.');
    ^

Error: Invalid transport, must be an object with a log method.
    at new LegacyTransportStream (C:\Users\Janez\Desktop\DiscordBot\node_modules\winston-transport\legacy.js:18:11)
    at DerivedLogger.add (C:\Users\Janez\Desktop\DiscordBot\node_modules\winston\lib\winston\logger.js:270:9)
    at Object.winston.(anonymous function).args [as add] (C:\Users\Janez\Desktop\DiscordBot\node_modules\winston\lib\winston.js:101:55)
    at Object.<anonymous> (C:\Users\Janez\Desktop\DiscordBot\bot.js:6:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)

C:\Users\Janez\Desktop\DiscordBot>

**Comment by lzlmike** [comment]
change the winston version from 3 to 2 in the package.json file as 
  "dependencies": {
    "discord.io": "^2.5.3",
    "winston": "2"
  }

**Comment by BenConnick** [comment]
I just used my own logging.
