### ISSUE TITLE
node bot.js issue

### ISSUE THREAD

**Issue by nickthebob** [renesansz/discord-greeter-bot#172]
So.. I followed all the steps as told, I just customized part of the coding description and name for the bot. I'm new to programming in general, so.. it'd be appreciated if I can get a response. I download what is needed at first, as well as the extra GitHub given in the bottom of the tutorial, (which was a update). After running node bot.js, I get this: C:\Users\Nikos\Desktop\IceTeaBot\node_modules\winston-transport\legacy.js:18
    throw new Error('Invalid transport, must be an object with a log method.');
    ^

Error: Invalid transport, must be an object with a log method.
    at new LegacyTransportStream (C:\Users\Nikos\Desktop\IceTeaBot\node_modules\winston-transport\legacy.js:18:11)
    at DerivedLogger.add (C:\Users\Nikos\Desktop\IceTeaBot\node_modules\winston\lib\winston\logger.js:270:9)
    at Object.winston.(anonymous function).args [as add] (C:\Users\Nikos\Desktop\IceTeaBot\node_modules\winston\lib\winston.js:101:55)
    at Object.<anonymous> (C:\Users\Nikos\Desktop\IceTeaBot\bot.js:6:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)

**Comment by SLia0** [comment]
If you copy pasted from a tutorial, delete the quotation marks and retype them. Some tutorials use symbols and not the actual readable text.

**Comment by BenConnick** [comment]
This error is related to the logging, which you do not actually need. 

Looking at the other open issues, it seems that this is pretty common. Others have commenting that replacing the winston dependency in the package.json file fixed the issue for them, but it did not fix it for me. 

As a workaround, you can delete all lines that have "logger" in them, and replace them with your own logging.
