### ISSUE TITLE
How to fix

### ISSUE THREAD

**Issue by HoStUUU** [renesansz/discord-greeter-bot#174]
throw new Error('Invalid transport, must be an object with a log method.');
    ^

Error: Invalid transport, must be an object with a log method.
    at new LegacyTransportStream (C:\Users\Olaf_\Desktop\Discordbot\node_modules\winston-transport\legacy.js:18:11)
    at DerivedLogger.add (C:\Users\Olaf_\Desktop\Discordbot\node_modules\winston\lib\winston\logger.js:270:9)
    at Object.winston.(anonymous function).args [as add] (C:\Users\Olaf_\Desktop\Discordbot\node_modules\winston\lib\winston.js:101:55)
    at Object.<anonymous> (C:\Users\Olaf_\Desktop\Discordbot\bot.js:6:8)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)

**Comment by JackkungTH** [comment]
Same here.

C:\Users\FlukyJackKung\Desktop\jackkungBot>node bot.js
C:\Users\FlukyJackKung\Desktop\jackkungBot\node_modules\winston-transport\legacy.js:18
    throw new Error('Invalid transport, must be an object with a log method.');
    ^

Error: Invalid transport, must be an object with a log method.
    at new LegacyTransportStream (C:\Users\FlukyJackKung\Desktop\jackkungBot\node_modules\winston-transport\legacy.js:18:11)
    at DerivedLogger.add (C:\Users\FlukyJackKung\Desktop\jackkungBot\node_modules\winston\lib\winston\logger.js:270:9)
    at Object.winston.(anonymous function).args [as add] (C:\Users\FlukyJackKung\Desktop\jackkungBot\node_modules\winston\lib\winston.js:101:55)
    at Object.<anonymous> (C:\Users\FlukyJackKung\Desktop\jackkungBot\bot.js:6:8)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)

**Comment by cosminghitea** [comment]
You need version 2.4.4 or create a transport for the Winston read the documentation for the version 3 or higher
