### ISSUE TITLE
Not run

### ISSUE THREAD

**Issue by JuventusITA** [renesansz/discord-greeter-bot#175]
module.js:550
    throw err;
    ^

Error: Cannot find module 'winston'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\mrkal\Desktop\Bho\bot.js:2:14)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

**Comment by cosminghitea** [comment]
Install version 2.4.4 of winston

**Comment by JuventusITA** [comment]
What?

Amir Kalaf

Il Lun 1 Ott 2018, 07:44 Cosmin.Ghitea <notifications@github.com> ha
scritto:

**Comment by cosminghitea** [comment]
in the package JSON the project is set to take the last version of the winston package if you will remove the caret then the project should work
