### ISSUE TITLE
Cannot find module.

### ISSUE THREAD

**Issue by Kosh25** [renesansz/discord-greeter-bot#180]
C:\Users\REDACTED\Desktop\mybot> node bot.js
module.js:550
    throw err;
    ^

Error: Cannot find module 'C:\Users\REDACTED\Desktop\mybot\bot.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

Anybody got any experience with this?

**Comment by Kosh25** [comment]
Tried using "node bot.json" and dragging the file into cmd but then I get this error:

_SyntaxError: C:\Users\REDACTED\Desktop\mybot\bot.json: Unexpected token v in JSON at position 2
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:672:27)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3_
