### ISSUE TITLE
stuck on node.js

### ISSUE THREAD

**Issue by boylej97** [renesansz/discord-greeter-bot#194]
![capture](https://user-images.githubusercontent.com/46059465/50367823-c887c200-057a-11e9-9b50-491f8573187c.PNG)
i have done everything that i can think possile

**Comment by jenaus** [comment]
same

**Comment by hotbutterytoast** [comment]
having the same problem

**Comment by rioplayz** [comment]
same

**Comment by Keyboard04** [comment]
Same here

SyntaxError: C:\Users\Valdemar\Desktop\Bot\auth.json: Unexpected token � in JSON at position 3
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:763:27)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\Valdemar\Desktop\Bot\bot.js:3:12)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)

**Comment by Keyboard04** [comment]
Wait, I know how to fix it! So, when you copy the auth.json it copies the quotation marks as fancy quotation marks. But most coding languages can't recognise those.
