### ISSUE TITLE
EJSONPARSE

### ISSUE THREAD

**Issue by SpringLocked** [renesansz/discord-greeter-bot#196]
So basically, I wanted to make a bot for a discord server, but since it's my first time doing this I have no idea on what went wrong. Can someone please help me?

Error:
npm ERR! file C:\Users\Jordan\Desktop\DiscordBot\package.json
npm ERR! code EJSONPARSE
npm ERR! JSON.parse Failed to parse json
 in JSON at position 2 while parsing '{"
npm ERR! JSON.parse �name�: �Circus Baby�,
npm ERR! JSON.parse �version�: �'
npm ERR! JSON.parse Failed to parse package.json data.
npm ERR! JSON.parse package.json must be actual JSON, not just JavaScript.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jordan\AppData\Roaming\npm-cache\_logs\2018-12-27T18_21_35_055Z-debug.log

C:\Users\Jordan\Desktop\DiscordBot>npm install discord.io winston --save
npm ERR! file C:\Users\Jordan\Desktop\DiscordBot\package.json
npm ERR! code EJSONPARSE
npm ERR! JSON.parse Failed to parse json
npm ERR! JSON.parse Unexpected token � in JSON at position 3 while parsing near '{
npm ERR! JSON.parse �name�: �Circus Baby...'
npm ERR! JSON.parse Failed to parse package.json data.
npm ERR! JSON.parse package.json must be actual JSON, not just JavaScript.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jordan\AppData\Roaming\npm-cache\_logs\2018-12-27T18_28_54_150Z-debug.log

This is the debug log:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'discord.io',
1 verbose cli   'winston',
1 verbose cli   '--save' ]
2 info using npm@6.4.1
3 info using node@v10.15.0
4 verbose npm-session 3cf29a049b769b45
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 timing stage:rollbackFailedOptional Completed in 6ms
8 timing stage:runTopLevelLifecycles Completed in 66ms
9 verbose stack Error: Failed to parse json
9 verbose stack Unexpected token � in JSON at position 3 while parsing near '{
9 verbose stack �name�: �Circus Baby...'
9 verbose stack     at parseError (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:452:11)
9 verbose stack     at parseJson (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:104:26)
9 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:51:5
9 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
9 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
10 verbose cwd C:\Users\Jordan\Desktop\DiscordBot
11 verbose Windows_NT 10.0.17134
12 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "discord.io" "winston" "--save"
13 verbose node v10.15.0
14 verbose npm  v6.4.1
15 error file C:\Users\Jordan\Desktop\DiscordBot\package.json
16 error code EJSONPARSE
17 error JSON.parse Failed to parse json
17 error JSON.parse Unexpected token � in JSON at position 3 while parsing near '{
17 error JSON.parse �name�: �Circus Baby...'
18 error JSON.parse Failed to parse package.json data.
18 error JSON.parse package.json must be actual JSON, not just JavaScript.
19 verbose exit [ 1, true ]

I've tried npm cache clean and that didn't work.

**Comment by SpringLocked** [comment]
And this is the package,json file if needed: 
{
“name”: “Circus Baby”,
“version”: “1.0.0”,
“description”: “She can sing.She can dance.She can take song requests with automated responses.She can even dispense ice cream.”,
“main”: “bot.js”,
“author”: “Afton Robotics”,
“dependencies”: {},
}

**Comment by Hamburglar0650** [comment]
Same issue here!
