### ISSUE TITLE
Syntax error? Umm....

### ISSUE THREAD

**Issue by Etanarvazac** [renesansz/discord-greeter-bot#20]
Okay so I went to test and got this. I don't know what's wrong. I've copied everything from the tutorial exactly.

```
module.js:657
    throw err;
    ^
SyntaxError: C:\Users\Etanarvazac Taseet\Desktop\Custom Discord Bot\auth.json: Unexpected token ) in JSON at position 76
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:654:27)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Etanarvazac Taseet\Desktop\Custom Discord Bot\bot.js:3:12)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
```

**Comment by Etanarvazac** [comment]
Not sure why the code field is not working...

**Comment by Etanarvazac** [comment]
Found it. I made a big error in the auth.json somehow. (Had the wrong symbol at the end of doc)
