### ISSUE TITLE
Can't use "userID"

### ISSUE THREAD

**Issue by Etanarvazac** [renesansz/discord-greeter-bot#21]
Code:
```
case 'dm':
      bot.createDMChannel(userID);
      to: userID
      message: 'Hi'
```

Error when ran:
```
c:\Users\Etanarvazac Taseet\Desktop\Custom Discord Bot\Test Bot 1\node_modules\discord.io\lib\index.js:923
                if (!err && goodResponse(res)) client._uIDToDM[res.body.recipient.id] = res.body.id;
                                                                                  ^

TypeError: Cannot read property 'id' of undefined
    at c:\Users\Etanarvazac Taseet\Desktop\Custom Discord Bot\Test Bot 1\node_modules\discord.io\lib\index.js:923:69
    at c:\Users\Etanarvazac Taseet\Desktop\Custom Discord Bot\Test Bot 1\node_modules\discord.io\lib\index.js:1464:13
    at Gunzip.onEnd (zlib.js:131:5)
    at emitNone (events.js:111:20)
    at Gunzip.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by Etanarvazac** [comment]
@renesansz
