### ISSUE TITLE
node bot.js issue

### ISSUE THREAD

**Issue by Justyndog** [renesansz/discord-greeter-bot#213]
I get this error when trying to run "node bot.js"

_Error: Cannot find module 'C:\Users\justy\bot.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)_

**Comment by BoredCook** [comment]
got the same error ..

**Comment by BoredCook** [comment]
also tryed to get this npm install https://github.com/woor/discord.io/tarball/gateway_v6 but i get warnings and nothing.
![Capture31](https://user-images.githubusercontent.com/48600611/54454318-79a48f80-4759-11e9-874d-c9ebf7f874d6.PNG)

**Comment by BoredCook** [comment]
This worked for me : npm install winston@2.2.0

**Comment by Carcabob** [comment]
> This worked for me : npm install winston@2.2.0

Hey, that worked for me too! Thanks!

**Comment by Yacuntaustralian** [comment]
it's not working for me
