### ISSUE TITLE
node bot.js issues

### ISSUE THREAD

**Issue by trollface19** [renesansz/discord-greeter-bot#216]
i keep getting this when i enter `node bot.js`

`SyntaxError: Invalid or unexpected token
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)`

**Comment by trollface19** [comment]
edit: changed some code, now im receiving this:
`at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)`

**Comment by MyUsernamesThis** [comment]
i get SyntaxError:  Unexpected Identifier

**Comment by renesansz** [comment]
can you post your codes here?
it says `SyntaxError: Invalid or unexpected token at new Script (vm.js:80:7) at createScript `

**Comment by trollface19** [comment]
i gave up on the idea... sorry for wasting your time.
