### ISSUE TITLE
Keep getting Invalid Transport Error

### ISSUE THREAD

**Issue by itsacrimetorhyme** [renesansz/discord-greeter-bot#224]
What does 
throw new Error('Invalid transport, must be an object with a log method.');
    ^

Error: Invalid transport, must be an object with a log method.
    at new LegacyTransportStream (C:\Users\Johnny\Desktop\Kammy2Bot\node_modules\winston-transport\legacy.js:18:11)
    at DerivedLogger.add (C:\Users\Johnny\Desktop\Kammy2Bot\node_modules\winston\lib\winston\logger.js:345:11)
    at Object.winston.<computed> [as add] (C:\Users\Johnny\Desktop\Kammy2Bot\node_modules\winston\lib\winston.js:110:68)
    at Object.<anonymous> (C:\Users\Johnny\Desktop\Kammy2Bot\bot.js:6:8)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:826:10)
    at internal/main/run_main_module.js:17:11
mean?
help?

**Comment by BedKitti** [comment]
Sorry, i can´t help, but SAME THING HERE!

Can Please anyone help?

**Comment by renesansz** [comment]
What version if Winston are you using?

**Comment by joewinsock** [comment]
pretty much the same issue here. i went into the winston folder of the package that was install via the link you provided in your tutorial. npm install discord.io winston --save so whatever version that installed

**Comment by joewinsock** [comment]
https://github.com/renesansz/discord-greeter-bot/issues/224#issuecomment-493310355 

In regards to my previous comment npm install winston@2.4.0 running that command fixed it.

**Comment by killrix** [comment]
![image](https://user-images.githubusercontent.com/53134619/61587233-dc90b200-aba3-11e9-92e9-95fc8dc05f42.png)
welcome bot not online please help
