### ISSUE TITLE
Cant set up a discord bot

### ISSUE THREAD

**Issue by Zdenster** [renesansz/discord-greeter-bot#225]
Here is my log:
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'discord.io',
1 verbose cli   'winston',
1 verbose cli   '--save'
1 verbose cli ]
2 info using npm@6.9.0
3 info using node@v12.0.0
4 verbose npm-session 1bc500b9a3360dd4
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 timing stage:rollbackFailedOptional Completed in 4ms
8 timing stage:runTopLevelLifecycles Completed in 26ms
9 verbose stack Error: Failed to parse json
9 verbose stack Unexpected token “ in JSON at position 3 while parsing near '{
9 verbose stack “name”: “zdensterovo...'
9 verbose stack     at parseError (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:452:11)
9 verbose stack     at parseJson (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:104:26)
9 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:51:5
9 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:90:16
9 verbose stack     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
10 verbose cwd C:\Users\Zdeněk\Pictures\Discord\Zdensterovo Komůrka\Bot\Kódy
11 verbose Windows_NT 6.3.9600
12 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "discord.io" "winston" "--save"
13 verbose node v12.0.0
14 verbose npm  v6.9.0
15 error file C:\Users\Zdeněk\Pictures\Discord\Zdensterovo Komůrka\Bot\Kódy\package.json
16 error code EJSONPARSE
17 error JSON.parse Failed to parse json
17 error JSON.parse Unexpected token “ in JSON at position 3 while parsing near '{
17 error JSON.parse “name”: “zdensterovo...'
18 error JSON.parse Failed to parse package.json data.
18 error JSON.parse package.json must be actual JSON, not just JavaScript.
19 verbose exit [ 1, true ]

**Comment by Zdenster** [comment]
I fixed it though i got another 1, log (in command prompt):
C:\Users\MyName\Pictures\Discord\ServerName\Bot\Codes\node bot.js 
internal/modules/cjs/loader.js:787
     throw err;
     ^

SyntaxError: C:\Users\MyName\Pictures\Discord\MyServer\Bot\Codes\auth.json: Unexpected toen " in JSON at position 3
     at JSON.parse (<anonymous>)
     at Object.Module._extensions..json (internal/modules/cjs/loader.js:784:27)
     at Module.load (internal/modules/cjs/loader.js:628:32)
     at Function.Module._load (internal/modules/cjs/loader.js:555:12)
     at Module.require (internal/modules/cjs/loader.js:666:19)
     at require (internal/modules/cjs/helpers.js:16:16)
     at Object.<anonymous> (C:\Users\MyName\Pictures\Discord\MyServer\Bot\Codes\bot.js:3:12)
     at Module._compile (internal/modules/cjs/loader.js:759:30)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
     at Module.load (internal/modules/cjs/loader.js:628:32)
