### ISSUE TITLE
I can't execute node bot.js

### ISSUE THREAD

**Issue by UndestinyALex** [renesansz/discord-greeter-bot#239]

**Comment by joypark** [comment]
what do you see when you run the command node bot.js?

**Comment by Ultimate73** [comment]
\Desktop\DiscordBot\auth.json: Unexpected token “ in JSON at position 3
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:976:27)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\conne\OneDrive\Desktop\DiscordBot\bot.js:3:12)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
