### ISSUE TITLE
Get an error when i execute node bot.js

### ISSUE THREAD

**Issue by Julian-van-Straten** [renesansz/discord-greeter-bot#240]
JMBP:Playlist Jules$ node bot.js
/Users/Jules/Playlist/bot.js:41
view rawbot.js hosted with ❤ by GitHub
     ^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3

**Comment by ApexPlayzGamez** [comment]
I'm having the same issue and I think it's something to do with the code not working or having wrong syntax.

**Comment by renesansz** [comment]
@Julian-van-Straten can you show your code?

In the error it says `Unexpected Identifier` in line 41 of your `bot.js`
