### ISSUE TITLE
npm install discord.io winston --save is not working

### ISSUE THREAD

**Issue by dhgtheecho** [renesansz/discord-greeter-bot#241]
I've followed the directions to a tee yet when i type that line all i get is this error code

C:\Users\JoelD\Greeting Bot>npm install discord.io --save
npm ERR! file C:\Users\JoelD\Greeting Bot\package.json
npm ERR! code EJSONPARSE
npm ERR! JSON.parse Failed to parse json
npm ERR! JSON.parse Unexpected token b in JSON at position 97 while parsing near '...ord Bot",
npm ERR! JSON.parse "main�: "bot.js",
npm ERR! JSON.parse "author�: ...'
npm ERR! JSON.parse Failed to parse package.json data.
npm ERR! JSON.parse package.json must be actual JSON, not just JavaScript.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\JoelD\AppData\Roaming\npm-cache\_logs\2019-10-20T18_44_42_439Z-debug.log

C:\Users\JoelD\Greeting Bot>node bot.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'discord.io'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\JoelD\Greeting Bot\bot.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by renesansz** [comment]
@dhgtheecho 
It seems you have an error with your package.json, it's having problem parsing the content.
Can you show your code here?

**Comment by BenHurricane** [comment]
If you copied and pasted, double check all " marks. Sometimes, when pasting, it will paste a "directional" quotation mark instead of the direction-neutral "
