### ISSUE TITLE
node bot.js

### ISSUE THREAD

**Issue by wasabbeh** [renesansz/discord-greeter-bot#254]
followed the tutorial. got this error.
C:\Users\abiga\Downloads\greeter-bot>node bot.js
internal/modules/cjs/loader.js:1193
    throw err;
    ^

SyntaxError: C:\Users\abiga\Downloads\greeter-bot\auth.json: Unexpected token D in JSON at position 0
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1190:22)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\abiga\Downloads\greeter-bot\bot.js:3:12)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)

C:\Users\abiga\Downloads\greeter-bot>

**Comment by Garg-Shashwat** [comment]
Same error here too

**Comment by IanDaBest** [comment]
this is what happened to me

internal/modules/cjs/loader.js:1032
  throw err;
  ^

Error: Cannot find module 'C:\Users\IanDaBest\Discord\DaBestBot\codes\bot.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:898:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}
