### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by PerksPrisoner** [renesansz/discord-greeter-bot#256]
**I resolved most of the issues but for some reason I can't resolve this... Guess it reaches beyong my knowledge.**

SyntaxError: C:\Users\Perks\Desktop\MCBot\auth.json: Unexpected token D in JSON at position 1
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1172:22)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\Perks\Desktop\MCBot\bot.js:3:12)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)

**This would be the auth.json line it seems to mention**

DISCORD_TOKEN=NzE1NDg5OTgyMzUzMTEzMDk4.Xs-U5Q.vlutAwOuQm-(REMOVED INFO)

**Comment by PerksPrisoner** [comment]
@renesansz
