### ISSUE TITLE
help i try to make my discord bot go online but it says this:

### ISSUE THREAD

**Issue by cometh8888** [renesansz/discord-greeter-bot#258]
SyntaxError: missing ) after argument list
←[90m    at wrapSafe (internal/modules/cjs/loader.js:1054:16)←[39m
←[90m    at Module._compile (internal/modules/cjs/loader.js:1102:27)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:986:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:879:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m

**Comment by sarthaktexas** [comment]
Can you please post your code?

**Comment by cometh8888** [comment]
const Discord = require('discord.js');
const bot = new Discord.client();

const ytdl = require("ytdl-core");
const token = "NzE3NDI0NDczMDE1NTgyODAx.XtcZkg.B9_HGqKyFpp1-_-768iMr-zy7ck";

bot .on('ready', () =>{
     console.log('this bot is online')
}

bot.login(token);
const PREFIX = "?";
var version = '1.2';
var servers = {};
const fs =require('fs');
bot.commands =new Discord.collection();

const commandFiles = fs.readdirSync('./commands/').filter(file => file.endsWith('.js'));
for(const file of commandFiles){
    const command = require(`./commands/${file}`);

    bot.commands.set(command.name, command);
}
























client.once('ready' , () => { 
     console.log('Doge music bot')
}):

bot.on('message', message => {
    let args = message.content.substring(PREFIX.lenght).split(" ")
    switch (args[0]) {
        case "play";

            function play(connetion, message){
                var serer =servers[message.guild.id];

                server.dispactcher = connection.playStream(ytdl{server.queue[0], {filer: "audioonly"}});

                server.queue.shift();

                server.dispatcher.on("end", function(){
                    if (server.queue{0}){
                        play(connection, message);
                    }else {
                        connection.disconnect();
                })


            }




        if (args{1}){
             message.channel.send("go to a gimme a link boi");
             return;
        }

        if(!message.member.voiceChannel){
            message.channel.send("you have to be in a voice channel boi");
            return;
        }

        if(!servers[message.guild.id]) servers[message.guild.id] = {
            queue: []
        }

        var server = servers[message.guild.id];

        server.queue.push(args[1]);

        if(!message.member.voice.connection) message.member.voiceChannel.join().then(function(connection)){
          play(connection, message);
        })
    


        break:

        case 'skip':
            var server = servers[message.guild.id];
            if (server.dispatcher) server.dispatcher.end();
            message.channel.send("skipping the song lmao!")
        break;

        case 'stop':
            var server = servers[message.guild.id]
            if(message.guild.voiceConnection){
                for(var i = server.queue.lenght -1; i >=0; i--){
                    server.queue.splice(i, 1);

                    server.dispatcher.end();
                    message.channel.send("ending the queue!")
                    console.log('stopped the queue')
                }

                if(message.guild.connection) message.guild.voiceConnection.disconnect();
        break;

    }


});

client.login(NzE3NDI0NDczMDE1NTgyODAx.XtcZkg.B9_HGqKyFpp1-_-768iMr-zy7ck);

**Comment by sarthaktexas** [comment]
don't ever release your token, change it in the developer console now!

**Comment by sarthaktexas** [comment]
try this
```js
const Discord = require("discord.js");
const bot = new Discord.client();

const ytdl = require("ytdl-core");
const token = "NzE3NDI0NDczMDE1NTgyODAx.XtcZkg.B9_HGqKyFpp1-_-768iMr-zy7ck";

const PREFIX = "?";
const fs = require("fs");
bot.commands = new Discord.collection();

const commandFiles = fs.readdirSync("./commands/").filter(file => file.endsWith(".js"));
for(const file of commandFiles){
const command = require(./commands/${file});

bot.commands.set(command.name, command);
}

bot.on("ready", () => {
console.log("this bot is online")
});

bot.on("ready" , () => {
console.log("Doge music bot")
});

bot.on("message", message => {
let args = message.content.substring(PREFIX.length).split(" ")
switch (args[0]) {
case "play";

        function play(connection, message){
            var server = servers[message.guild.id];

            server.dispatcher = connection.playStream(ytdl{server.queue[0], {filer: "audioonly"}});

            server.queue.shift();

            server.dispatcher.on("end", function(){
                if (server.queue{0}){
                    play(connection, message);
                }else {
                    connection.disconnect();
            })


        }




    if (args{1}){
         message.channel.send("go to a gimme a link boi");
         return;
    }

    if(!message.member.voiceChannel){
        message.channel.send("you have to be in a voice channel boi");
        return;
    }

    if(!servers[message.guild.id]) servers[message.guild.id] = {
        queue: []
    }

    var server = servers[message.guild.id];

    server.queue.push(args[1]);

    if(!message.member.voice.connection) message.member.voiceChannel.join().then(function(connection)){
      play(connection, message);
    })



    break:

    case 'skip':
        var server = servers[message.guild.id];
        if (server.dispatcher) server.dispatcher.end();
        message.channel.send("skipping the song lmao!")
    break;

    case 'stop':
        var server = servers[message.guild.id]
        if(message.guild.voiceConnection){
            for(var i = server.queue.length -1; i >=0; i--){
                server.queue.splice(i, 1);

                server.dispatcher.end();
                message.channel.send("ending the queue!")
                console.log("stopped the queue")
            }

            if(message.guild.connection) message.guild.voiceConnection.disconnect();
    break;

}
});
bot.login(token);
```

**Comment by cometh8888** [comment]
oke thx

**Comment by cometh8888** [comment]
wait its still saying the same error
