### ISSUE TITLE
Line 1 error expected object

### ISSUE THREAD

**Issue by capjay45** [renesansz/discord-greeter-bot#279]
Hi, I know pretty much nothing about js but I keep getting this issue and I dont know how to solve it
Script: C:/Users/myname/Desktopdiscordbot/bot.js
Line: 1
Char: 1
Error: Object expected
Code: numbers
Source: Microsoft JScript runtime error

**Comment by sarthaktexas** [comment]
Looks like you're running this by clicking on it. Try running it by opening `cmd.exe` and typing `cd Desktopdiscordbot && node bot.js`.

**Comment by xBlanco** [comment]
I had the same issue, and when I loaded by the cmd, it says me that:

SyntaxError: C:\Users\Usuario\Desktop\jesus-bot\auth.json: Unexpected token D in JSON at position 0
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1106:22)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\Usuario\Desktop\jesus-bot\bot.js:3:12)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
