### ISSUE TITLE
discord bot wont go online

### ISSUE THREAD

**Issue by DoctorCheese1** [renesansz/discord-greeter-bot#280]
hello renesansz, 

I have done everything in order three times. I can't figure how to make it go online. please help. 

thanks,
Doctor Cheese

**Comment by DoctorCheese1** [comment]
this is wat is says:


(node:11620) UnhandledPromiseRejectionWarning: Error [TOKEN_INVALID]: An invalid token was provided.
    at Client.login (C:\Users\theon\discord-greeter-bot\discord-greeter-bot\node_modules\discord.js\src\client\Client.js:206:52)
    at Object.<anonymous> (C:\Users\theon\discord-greeter-bot\discord-greeter-bot\bot.js:17:8)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11620) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11620) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by sarthaktexas** [comment]
The token is incorrect — make sure you put the right one.

**Comment by sarthaktexas** [comment]
remind me not to ever reply to pr's through email...

**Comment by DoctorCheese1** [comment]
ok thanks
