### ISSUE TITLE
bot.js giving "cannot find module discord.io"

### ISSUE THREAD

**Issue by keyosbringer** [renesansz/discord-greeter-bot#49]
D:\Discord bot>node bot.js
module.js:540
    throw err;
    ^

Error: Cannot find module 'discord.io'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Discord bot\bot.js:1:77)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

How do I fix this? There is a folder called "discord.io" in the "Discord bot" folder but it isn't noticing it?

**Comment by sarthaktexas** [comment]
Are you sure it's in the same directory as the ```bot.js```?

**Comment by keyosbringer** [comment]
yeah, the folder is in the same directory as bot.js.

**Comment by keyosbringer** [comment]
well I deleted the files, downloaded them again, and now when i typed in node bot.js, nothing happens

**Comment by axelgreavette** [comment]
download the woor gateway with git
