### ISSUE TITLE
Followed Steps, Not Starting

### ISSUE THREAD

**Issue by samjoycewoof** [renesansz/discord-greeter-bot#7]
I followed all steps detailed in the tutorial and I installed everything correctly, but I get this error when I run the code on my computer. 

SyntaxError: /Users/sam/Documents/sam_bot/auth.json: Unexpected token 
 in JSON at position 15
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:587:27)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/sam/Documents/sam_bot/bot.js:4:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

I haven't editted any parts of the code, I just tried this as a first test of the bot.

**Comment by Nomad21** [comment]
Are you copying the token from your discord developer page as explained [here](https://github.com/reactiflux/discord-irc/wiki/Creating-a-discord-bot-&-getting-a-token) ?. Also remove any spaces and the start and end of the token.
