### ISSUE TITLE
SyntaxError: Unexpected token }

### ISSUE THREAD

**Issue by Lugox** [renesansz/discord-greeter-bot#71]
C:\Users\NAME\Documents\Codes\GreeterBot>node bot.js
C:\Users\NAME\Documents\Codes\GreeterBot\bot.js:36
         }
         ^

SyntaxError: Unexpected token }
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

C:\Users\NAME\Documents\Codes\GreeterBot>

**Comment by Lugox** [comment]
I've changed my "case "ping";" into case "ping"," because I was getting a SyntaxError on my 30th line in the bot.js file. However, currently, I am receiving a different SyntaxError and  this one is telling me to remove all (, { and ; (break as well on line 34)

**Comment by GingkathFox** [comment]
XP
I think thats just JS acting up ;-;

**Comment by GingkathFox** [comment]
did u remove the breaks?
