### ISSUE TITLE
Mac Node error

### ISSUE THREAD

**Issue by GingkathFox** [renesansz/discord-greeter-bot#75]
I tried running "Node bot.js", and this is the error I got:
```SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by GingkathFox** [comment]
Dupe of #71
